### ISSUE TITLE
Cant't install usage, got a build error in my system

### ISSUE THREAD

**Issue by maxbbn** [arunoda/node-usage#21]
```
...

> usage@0.3.9 install /home/wenlong/.nvm/v0.11.9/lib/node_modules/pm2/node_modules/usage
> node-gyp rebuild

make: Entering directory `/home/wenlong/.nvm/v0.11.9/lib/node_modules/pm2/node_modules/usage/build'
  CXX(target) Release/obj.target/sysinfo/src/binding.o
../src/binding.cpp:20:38: warning: no newline at end of file
/home/wenlong/.node-gyp/0.11.9/src/node.h:188: error: ‘ssize_t’ does not name a type
/home/wenlong/.node-gyp/0.11.9/src/node.h:192: error: ‘ssize_t’ does not name a type
make: *** [Release/obj.target/sysinfo/src/binding.o] Error 1
make: Leaving directory `/home/wenlong/.nvm/v0.11.9/lib/node_modules/pm2/node_modules/usage/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/wenlong/.nvm/v0.11.9/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:101:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:827:12)
gyp ERR! System Linux 2.6.18-308.el5
gyp ERR! command "node" "/home/wenlong/.nvm/v0.11.9/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/wenlong/.nvm/v0.11.9/lib/node_modules/pm2/node_modules/usage
gyp ERR! node -v v0.11.9
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok

...


npm ERR! usage@0.3.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the usage@0.3.9 install script.
npm ERR! This is most likely a problem with the usage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls usage
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.18-308.el5
npm ERR! command "/home/wenlong/.nvm/v0.11.9/bin/node" "/home/wenlong/.nvm/v0.11.9/bin/npm" "i" "pm2" "-g"
npm ERR! cwd /home/wenlong
npm ERR! node -v v0.11.9
npm ERR! npm -v 1.3.15
npm ERR! code ELIFECYCLE
npm http 200 https://registry.npmjs.org/keypress
npm http GET https://registry.npmjs.org/keypress/-/keypress-0.1.0.tgz
npm http 200 https://registry.npmjs.org/keypress/-/keypress-0.1.0.tgz
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/wenlong/npm-debug.log
npm ERR! not ok code 0

```

**Comment by myhere** [comment]
+1 have the same error :(
