### ISSUE TITLE
Installing on FreeBSD 10, g++ error

### ISSUE THREAD

**Issue by josser** [arunoda/node-usage#24]
Hi, trying to install 'usage' on freebsd 10 and got build error: 

``` bash
npm install usage
npm http GET https://registry.npmjs.org/usage
npm http 200 https://registry.npmjs.org/usage
npm http GET https://registry.npmjs.org/usage/-/usage-0.3.9.tgz
npm http 200 https://registry.npmjs.org/usage/-/usage-0.3.9.tgz
npm http GET https://registry.npmjs.org/bindings
npm http 200 https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/bindings/-/bindings-1.2.0.tgz
npm http 200 https://registry.npmjs.org/bindings/-/bindings-1.2.0.tgz

> usage@0.3.9 install /usr/home/josser/test/node_modules/usage
> node-gyp rebuild

gyp http GET http://nodejs.org/dist/v0.10.26/node-v0.10.26.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.26/node-v0.10.26.tar.gz
gmake: Вход в каталог `/usr/home/josser/test/node_modules/usage/build'
  CXX(target) Release/obj.target/sysinfo/src/binding.o
gmake: g++: Команда не найдена // Command not found
gmake: *** [Release/obj.target/sysinfo/src/binding.o] Ошибка 127
gmake: Выход из каталога `/usr/home/josser/test/node_modules/usage/build'
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System FreeBSD 10.0-RELEASE
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/josser/test/node_modules/usage
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0
```

I'm not very good in all this compiler-releated questions so I don't know is that issue in usage or in freebsd itself. 
The only thing I understand is FreeBSD 10 came with clang as a default system compiler. So if g++ is hardcoded somewhere in usage makefiles, that can lead to build error. 

Sorry for bad english and ugly bug-report :D

**Comment by josser** [comment]
Not actual anymore
